apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: charm
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: adityapb/charm-netlrts:latest
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - /app/charmrun
            args:
            - +p2
            - /app/jacobi2d
            - "4000"
            - "200"
            - +balancer
            - GreedyLB
            - +LBDebug
            - "3"
            - ++nodelist
            - /etc/mpi/hostfile
            - ++server
            - ++server-port
            - "1234"
            resources:
              limits:
                cpu: 1
                memory: 1Gi
    Worker:
      replicas: 4
      template:
        spec:
          containers:
          - image: us.icr.io/charm-registry/charm-netlrts:dev2
            name: mpi-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: 1
                memory: 4Gi
          imagePullSecrets:
            - name: all-icr-io
        securityContext:
            fsGroup: 1001
            runAsUser: 1001
            runAsGroup: 1001
