
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: charm-0
spec:
  slotsPerWorker: 1
  priority: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 600
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      maxReplicas: 1
      template:
        spec:
          containers:
          - image: adityapb/charm-netlrts:dev-new
            imagePullPolicy: Always
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - /app/charmrun
            args:
            - /app/jacobi2d
            - "8192"
            - "512"
            - "600"
            - +balancer
            - MetisLB
            - +LBDebug
            - "3"
            - ++verbose
            resources:
              limits:
                cpu: 1
    Worker:
      minReplicas: 1
      maxReplicas: 10
      template:
        spec:
          containers:
          - image: adityapb/charm-netlrts:dev-new
            imagePullPolicy: Always
            name: mpi-worker
            volumeMounts:
            - mountPath: /dev/shm
              name: shm-volume
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: 1
          volumes:
            - name: shm-volume
              emptyDir:
                medium: Memory
                sizeLimit: 1Gi
